name: Destroy Terraform

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: eu-north-1
      TF_VAR_ami_id: ami-0b46816ffa1234887
      TF_VAR_instance_type: t3.micro
      TF_VAR_vpc_id: vpc-0391cb4eb38e57302      
      TF_VAR_instance_name: cal-com
      TF_VAR_security_group_name: cal-sg
      TF_VAR_key_name: test-key
      TF_VAR_assume_role: arn:aws:iam::${{ secrets.Account_ID}}:role/TerraformBootstrapRole

      # ingress_rules as JSON
      TF_VAR_ingress_rules: >
        [
          {
            "from_port": 3000,
            "to_port": 3000,
            "protocol": "tcp",
            "cidr": "0.0.0.0/0"
          },
          {
            "from_port": 443,
            "to_port": 443,
            "protocol": "tcp",
            "cidr": "0.0.0.0/0"
          },
          {
            "from_port": 80,
            "to_port": 80,
            "protocol": "tcp",
            "cidr": "0.0.0.0/0"
          }
        ]

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.Account_ID }}:role/GitHubTerraformRole
          aws-region: eu-north-1

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Check Terraform state lock
        id: lock
        run: |
          ITEM=$(aws dynamodb get-item \
            --table-name terraform-locks \
            --key '{
              "LockID": { "S": "terraform-state-file-maintenance/ec2/terraform.tfstate" }
            }')

          LOCK_ID=$(echo "$ITEM" | jq -r '.Item.Info.S // empty | fromjson? | .ID')

          if [ -n "$LOCK_ID" ]; then
            echo "Terraform state is locked: $LOCK_ID"
            echo "lock_id=$LOCK_ID" >> $GITHUB_OUTPUT
          else
            echo "No Terraform lock found"
          fi


      - name: Terraform Destroy
        run: terraform destroy --auto-approve

      